name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:

# Cancel any runs in progress -- just complete the latest run
concurrency: 
  group: github_pages
  cancel-in-progress: true

jobs:
  github-pages:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:     
    
      # Jekyll Picture Tag requires libvips libraries for resizing images, which must be installed
      - name: Install JPT's dependencies
        run: sudo apt-get install libvips-tools
        
      - name: Checkout repo
        uses: actions/checkout@v2          
            
      # Install the proper version of Ruby and run bundle install
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
        
      - name: Run images script
        run: |
         chmod +x ./assets/images/_resizeimages.sh
         cd ./assets/images
         ./_resizeimages.sh
        shell: bash      
                            
      # Build the site
      - name: Jekyll build
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          
      # Push changes back to Github
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commited by github actions
                  
#      # Publish built site to Pages
#      - name: 🚀 deploy
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: gh-pages
#          folder: _site
#          force: false

      # Install SSH Key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
       
      # Update known_hosts 
      - name: Adding Known Hosts
        run: ssh-keyscan -t dsa -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Publish built site to Akamai Netstorage
      - name: Deploy with rsync
        run: rsync -avz -e 'ssh -oHostKeyAlgorithms=+ssh-dss' ./_site/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/350001/rlw7w/

