name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install imagemagick 
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.TOKEN }}
