name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:          
        
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Run images script
        run: |
         chmod +x ./assets/images/_resizeimages.sh
         cd ./assets/images
         ./_resizeimages.sh
        shell: bash
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: resized images
        
      - name: Create Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.TOKEN }}
          pre_build_commands: |
            apk --update add vips vips-tools

      - name: Make Purge Request
        id: myRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: http://rlw7w.uk/purge/${{ secrets.PURGE }}
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}


